# This is a basic workflow to help you get started with Actions

name: Publish To Maven Central

# Controls when the workflow will run
on:
  # Triggers the workflow when tag is pushed
  push:
    tags: .*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: default

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: publish
        run: ./gradlew publish --no-daemon --no-parallel
